spring:
  application:
    name: employee-service
  output:
    ansi:
      enabled: always
  cloud:
    kubernetes:
      discovery:
        include-not-ready-addresses: true
        all-namespaces: true
      config:
        name: employee-service
        namespace: adnan-mama-dev
        sources:
          - name: adnan-mama-dev

management:
  endpoint:
    service-registry:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
   com.example: debug
